site_name: Consulta CEP
repo_url: https://github.com/r1cardopereira/consulta_cep
repo_name: r1cardopereira/consulta_cep
edit_uri: tree/master/docs
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to Dark Mode
    accent: pink
    primary: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to Light Mode
    scheme: dark
 
markdown_extensions:
  - attr_list

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [consulta_cep]